# Generated by Django 4.1.1 on 2023-04-07 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('heart', models.IntegerField(verbose_name='心率')),
                ('blood', models.IntegerField(verbose_name='血氧')),
                ('body_status', models.SmallIntegerField(choices=[(1, '正常'), (2, '异常')], default=1, verbose_name='身体状况')),
                ('GPS_log', models.CharField(max_length=64, verbose_name='经度')),
                ('GPS_lat', models.CharField(max_length=64, verbose_name='纬度')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('temperature', models.CharField(max_length=64, verbose_name='温度')),
                ('humid', models.CharField(max_length=64, verbose_name='湿度')),
                ('smoke_status', models.SmallIntegerField(choices=[(1, '正常'), (2, '异常')], default=1, verbose_name='烟雾报警')),
                ('door_status', models.SmallIntegerField(choices=[(1, '正常'), (2, '异常')], default=1, verbose_name='门磁报警')),
                ('air_status', models.SmallIntegerField(choices=[(1, '高'), (2, '中'), (3, '低')], default=1, verbose_name='空气质量')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('temperature', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='温度')),
                ('humid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='湿度')),
                ('smoke_status', models.SmallIntegerField(choices=[(1, '正常'), (2, '异常')], default=1, verbose_name='烟雾报警')),
                ('door_status', models.SmallIntegerField(choices=[(1, '正常'), (2, '异常')], default=1, verbose_name='门磁报警')),
                ('air_status', models.SmallIntegerField(choices=[(1, '高'), (2, '中'), (3, '低')], default=1, verbose_name='空气质量')),
                ('heart', models.IntegerField(verbose_name='心率')),
                ('blood', models.IntegerField(verbose_name='血氧')),
                ('body_status', models.SmallIntegerField(choices=[(1, '正常'), (2, '异常')], default=1, verbose_name='身体状况')),
                ('GPS', models.CharField(max_length=64, verbose_name='GPS')),
            ],
        ),
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('level', models.SmallIntegerField(choices=[(1, '1级'), (2, '2级'), (3, '3级'), (4, '4级')], default=1, verbose_name='级别')),
                ('status', models.SmallIntegerField(choices=[(1, '已占用'), (2, '未使用')], default=2, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='账户余额')),
                ('create_time', models.DateField(verbose_name='入职时间')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', verbose_name='部门')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, '紧急'), (2, '重要'), (3, '临时')], default=1, verbose_name='级别')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('detail', models.TextField(verbose_name='详细信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='负责人')),
            ],
        ),
    ]
